// ADMIN
export const ADD_SHOWING_CITY = 'ADD_SHOWING_CITY'
export const REMOVE_SHOWING_CITY = 'REMOVE_SHOWING_CITY'
export const REMOVE_SHOWING_DATE = 'REMOVE_SHOWING_DATE'
export const UPDATE_SHOWING_DATE = 'UPDATE_SHOWING_DATE'
export const ADD_SHOWING_DATE = 'ADD_SHOWING_DATE'
export const UPDATE_FILM_NAME = 'UPDATE_FILM_NAME'
export const UPDATE_FILM_URL = 'UPDATE_FILM_URL'
export const UPDATE_FILM_TRAILER = 'UPDATE_FILM_TRAILER'
export const UPDATE_FILM_FULL_DESCRIPTION = 'UPDATE_FILM_FULL_DESCRIPTION'
export const UPDATE_FILM_SHORT_DESCRIPTION = 'UPDATE_FILM_SHORT_DESCRIPTION'
export const UPDATE_FILM_DESKTOP_IMAGE = 'UPDATE_FILM_DESKTOP_IMAGE'
export const UPDATE_FILM_MOBILE_IMAGE = 'UPDATE_FILM_MOBILE_IMAGE'

// APP
export const SET_FILM_DATES = 'SET_FILM_DATES'
export const SELECT_DATE = 'SELECT_DATE'
export const SELECT_LOCATION = 'SELECT_LOCATION'
export const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST'
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS'
export const GET_FILMS_ERROR = 'GET_FILMS_ERR0R'
export const SAVE_FILM_REQUEST = 'SAVE_FILM_REQUEST'
export const SAVE_FILM_SUCCESS = 'SAVE_FILM_SUCCESS'
export const SAVE_FILM_ERROR = 'SAVE_FILM_ERROR'

// UI

// main
export const UI_SHOW_TRAILER = 'SHOW_TRAILER'
export const UI_HIDE_TRAILER = 'HIDE_TRAILER'
export const UI_SHOW_MAP = 'SHOW_MAP'
export const UI_HIDE_MAP = 'HIDE_MAP'
export const UI_SHOW_LOCATION_MENU = 'SHOW_LOCATION_MENU'
export const UI_HIDE_LOCATION_MENU = 'HIDE_LOCATION_MENU'
export const UI_SHOW_LOADER = 'UI_SHOW_LOADER'
export const UI_HIDE_LOADER = 'UI_HIDE_LOADER'

// admin
export const UI_ADD_SELECTED_SHOWING_DATE_FOR_CITY = 'UI_SELECT_DATE_FOR_CITY'
export const UI_REMOVE_SELECTED_SHOWING_DATE_FOR_CITY = 'UI_REMOVE_SELECTED_SHOWING_DATE_FOR_CITY'
